/// <reference types="npm:@types/react@18.3.1" />
// Shared Sprouts brand tokens for all transactional email templates.
export const brand = {
  fontFamily:
    '"Plus Jakarta Sans", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif',
  bodyBg: '#ffffff',
  surface: '#ffffff',
  surfaceMuted: '#f5f3ff',
  border: '#ede9fe',
  text: '#1a1033',
  textMuted: '#4a4458',
  textSubtle: '#8b8694',
  primary: '#7c3aed',
  success: '#16a34a',
  warning: '#d97706',
  danger: '#dc2626',
  appUrl: 'https://sprouts.littlegreenhearts.com',
  supportEmail: 'hello@littlegreenhearts.com',
  brandLabel: 'SPROUTS',
} as const

export const styles = {
  main: { backgroundColor: brand.bodyBg, fontFamily: brand.fontFamily },
  container: { padding: '32px 28px', maxWidth: '600px', margin: '0 auto' },
  brandMark: {
    fontSize: '11px',
    fontWeight: '800' as const,
    color: brand.primary,
    letterSpacing: '0.3em',
    margin: '0 0 16px',
  },
  h1: {
    fontSize: '24px',
    fontWeight: '700' as const,
    color: brand.text,
    margin: '0 0 12px',
    letterSpacing: '-0.01em',
  },
  h2: {
    fontSize: '18px',
    fontWeight: '700' as const,
    color: brand.text,
    margin: '20px 0 8px',
  },
  lead: {
    fontSize: '15px',
    color: brand.textMuted,
    lineHeight: '1.6',
    margin: '0 0 16px',
  },
  text: {
    fontSize: '14px',
    color: brand.textMuted,
    lineHeight: '1.7',
    margin: '0 0 16px',
  },
  smallText: {
    fontSize: '13px',
    color: brand.textSubtle,
    lineHeight: '1.5',
    margin: '8px 0 0',
  },
  card: {
    padding: '20px 24px',
    backgroundColor: brand.surface,
    border: `1px solid ${brand.border}`,
    borderRadius: '14px',
    marginBottom: '16px',
  },
  heroBox: {
    padding: '28px 24px',
    backgroundColor: brand.surfaceMuted,
    borderRadius: '18px',
    marginBottom: '20px',
    textAlign: 'center' as const,
  },
  button: {
    backgroundColor: brand.primary,
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '600' as const,
    borderRadius: '12px',
    padding: '13px 26px',
    textDecoration: 'none',
    display: 'inline-block',
  },
  buttonGhost: {
    backgroundColor: '#ffffff',
    color: brand.primary,
    border: `2px solid ${brand.primary}`,
    fontSize: '14px',
    fontWeight: '600' as const,
    borderRadius: '12px',
    padding: '11px 22px',
    textDecoration: 'none',
    display: 'inline-block',
  },
  hr: { border: 'none', borderTop: `1px solid ${brand.border}`, margin: '24px 0' },
  footer: { fontSize: '12px', color: brand.textSubtle, lineHeight: '1.6', margin: '0 0 6px' },
  signoff: { fontSize: '12px', color: brand.textSubtle, margin: '0' },
  link: { color: brand.primary, textDecoration: 'underline' },
  amount: {
    fontSize: '32px',
    fontWeight: '800' as const,
    color: brand.text,
    margin: '4px 0',
    letterSpacing: '-0.02em',
  },
  amountLabel: {
    fontSize: '11px',
    fontWeight: '700' as const,
    color: brand.primary,
    letterSpacing: '0.2em',
    margin: '0',
    textTransform: 'uppercase' as const,
  },
  badge: {
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: '999px',
    fontSize: '11px',
    fontWeight: '700' as const,
    letterSpacing: '0.04em',
  },
  row: {
    padding: '10px 0',
    borderBottom: `1px solid ${brand.border}`,
    fontSize: '14px',
    color: brand.textMuted,
  },
  rowLabel: {
    color: brand.textSubtle,
    fontSize: '12px',
    margin: '0 0 2px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    fontWeight: '700' as const,
  },
  rowValue: { color: brand.text, fontSize: '15px', margin: '0', fontWeight: '600' as const },
}